# Generated by Django 3.1.7 on 2021-05-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_auto_20210427_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('PAYMENT SUCCESSFUL', 'PAYMENT SUCCESSFUL')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_no', models.CharField(max_length=20)),
                ('bank_account_name', models.CharField(max_length=40)),
                ('IFSC', models.CharField(max_length=20)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.account')),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.request')),
            ],
        ),
    ]
